### ISSUE TITLE
The B evil-ex-command could work with evil visual blocks

### ISSUE THREAD

**Issue by ninrod** [noctuid/rect-ext.el#2]
so after 33f351c16f240b0719e7ab64ef98c6df595d0c2f, I've tried to use the B command in a vim visual block selection `C-v` to no success. rectangular selection is working spectacularly, provided that one escapes the command correctly:

```viml
:`<,`>B s/text/new/g
```

consider adding support for evil visual blocks.

**Comment by noctuid** [comment]
Could you describe what goes wrong? It is working for me.

**Comment by ninrod** [comment]
you're right it is working, I just screw up.
